// Code generated by goctl. DO NOT EDIT.
// Source: domainRpc.proto

package server

import (
	"context"

	"github.com/delyr1c/dechoric/src/domain/domainRpc/domainRpc"
	"github.com/delyr1c/dechoric/src/domain/domainRpc/internal/logic"
	"github.com/delyr1c/dechoric/src/domain/domainRpc/internal/svc"
)

type DomainRpcServer struct {
	svcCtx *svc.ServiceContext
	domainRpc.UnimplementedDomainRpcServer
}

func NewDomainRpcServer(svcCtx *svc.ServiceContext) *DomainRpcServer {
	return &DomainRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *DomainRpcServer) Ping(ctx context.Context, in *domainRpc.Request) (*domainRpc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
