// Code generated by goctl. DO NOT EDIT.

package lotteryHistory

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	lotteryHistoryFieldNames          = builder.RawFieldNames(&LotteryHistory{})
	lotteryHistoryRows                = strings.Join(lotteryHistoryFieldNames, ",")
	lotteryHistoryRowsExpectAutoSet   = strings.Join(stringx.Remove(lotteryHistoryFieldNames, "`history_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	lotteryHistoryRowsWithPlaceHolder = strings.Join(stringx.Remove(lotteryHistoryFieldNames, "`history_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	lotteryHistoryModel interface {
		Insert(ctx context.Context, data *LotteryHistory) (sql.Result, error)
		FindOne(ctx context.Context, historyId uint64) (*LotteryHistory, error)
		QueryStrategyAwardHistoryCount(ctx context.Context, userId string)(int ,error)
		QueryStrategyAwardHistory(ctx context.Context, userId string, page, pageSize int) ([]LotteryHistory, error)
		Update(ctx context.Context, data *LotteryHistory) error
		Delete(ctx context.Context, historyId uint64) error
	}

	defaultLotteryHistoryModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LotteryHistory struct {
		HistoryId  uint64         `db:"history_id"`  // 自增ID
		UserId     string         `db:"user_id"`     // 用户ID
		TreeDesc   sql.NullString `db:"tree_desc"`   // 历史记录叙述
		Prize      string         `db:"prize"`       // 奖品描述
		CreateTime time.Time      `db:"create_time"` // 记录创建时间
	}
)

func newLotteryHistoryModel(conn sqlx.SqlConn) *defaultLotteryHistoryModel {
	return &defaultLotteryHistoryModel{
		conn:  conn,
		table: "`lottery_history`",
	}
}

func (m *defaultLotteryHistoryModel) Delete(ctx context.Context, historyId uint64) error {
	query := fmt.Sprintf("delete from %s where `history_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, historyId)
	return err
}

func (m *defaultLotteryHistoryModel) FindOne(ctx context.Context, historyId uint64) (*LotteryHistory, error) {
	query := fmt.Sprintf("select %s from %s where `history_id` = ? limit 1", lotteryHistoryRows, m.table)
	var resp LotteryHistory
	err := m.conn.QueryRowCtx(ctx, &resp, query, historyId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLotteryHistoryModel) Insert(ctx context.Context, data *LotteryHistory) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, lotteryHistoryRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.TreeDesc, data.Prize)
	return ret, err
}

func (m *defaultLotteryHistoryModel) Update(ctx context.Context, data *LotteryHistory) error {
	query := fmt.Sprintf("update %s set %s where `history_id` = ?", m.table, lotteryHistoryRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.TreeDesc, data.Prize, data.HistoryId)
	return err
}

func (m *defaultLotteryHistoryModel) tableName() string {
	return m.table
}
func (m *defaultLotteryHistoryModel) QueryStrategyAwardHistoryCount(ctx context.Context, userId string)(int ,error){
	// 查询符合条件的总记录数
	countQuery := fmt.Sprintf("SELECT COUNT(*) FROM %s WHERE user_id = ?", m.table)
	var totalCount int
	err := m.conn.QueryRowCtx(ctx, &totalCount, countQuery, userId)
	if err != nil {
		return 0, err
	}
	return totalCount,nil
}
func (m *defaultLotteryHistoryModel) QueryStrategyAwardHistory(ctx context.Context, userId string, page, pageSize int) ([]LotteryHistory, error) {
	// 计算 offset
	offset := (page - 1) * pageSize
	
	// 构建 SQL 查询
	query := fmt.Sprintf("SELECT %s FROM %s WHERE user_id = ? LIMIT ? OFFSET ?", lotteryHistoryRows, m.table)
	histories := make([]LotteryHistory, 0)
	
	// 执行查询并传递 userId, pageSize, offset 参数
	err := m.conn.QueryRowsCtx(ctx, &histories, query, userId, pageSize, offset)
	if err != nil {
		return nil, err
	}

	return histories, nil
}
